class_name Lang
extends RefCounted
## Whole-game localisation. English is the source language; every interface
## string is looked up through Godot's TranslationServer (tr(), and automatically
## for Label/Button text). Story text lives in StoryData with both languages inline.

static var _ready := false


static func setup() -> void:
	if _ready:
		return
	_ready = true
	var t := Translation.new()
	t.locale = "ar"
	for k in AR:
		t.add_message(k, AR[k])
	TranslationServer.add_translation(t)


static func apply(lang: String) -> void:
	TranslationServer.set_locale(lang)


static func is_ar() -> bool:
	return TranslationServer.get_locale().begins_with("ar")


static func t(s: String) -> String:
	return TranslationServer.translate(s)


const AR := {
	# ---------------------------------------------------------------- menus
	"Continue": "متابعة",
	"New Game": "لعبة جديدة",
	"Settings": "الإعدادات",
	"Credits": "الشكر والحقوق",
	"Quit": "خروج",
	"Quit to desktop": "الخروج إلى سطح المكتب",
	"Back": "رجوع",
	"Resume": "استئناف",
	"Save game": "حفظ اللعبة",
	"Controls": "التحكم",
	"Save & main menu": "حفظ والعودة للقائمة",
	"Save & quit": "حفظ وخروج",
	"Paused": "إيقاف مؤقت",
	"Cancel": "إلغاء",
	"Start over": "البدء من جديد",
	"Erase everything and start over": "مسح كل شيء والبدء من الصفر",
	"Start over from the very beginning?": "البدء من البداية تمامًا؟",
	"Your island, your journal, your choices and every day you survived will be erased forever. This cannot be undone.":
		"جزيرتك ويومياتك واختياراتك وكل يوم نجوت فيه ستُمحى إلى الأبد. لا يمكن التراجع عن هذا.",
	"Type ERASE to confirm": "اكتب ERASE للتأكيد",
	"Erase and start over": "امسح وابدأ من جديد",
	"Replay the prologue": "إعادة مشاهدة المقدمة",
	"Day %d": "اليوم %d",
	"Day %d · %s": "اليوم %d · %s",
	"Last played %s": "آخر لعب %s",
	"One island. Every story is yours alone.": "جزيرة واحدة. وكل قصة لك وحدك.",
	"Press any key": "اضغط أي زر",
	"Early access build": "نسخة الوصول المبكر",
	"Reset tab to defaults": "استعادة الافتراضي لهذا القسم",
	"Press a key…  (Esc to cancel)": "اضغط زرًا…  (Esc للإلغاء)",
	"Default": "الافتراضي",
	"LMB": "الزر الأيسر",
	"RMB": "الزر الأيمن",
	"Use tool · hold to carry": "استخدام الأداة · استمر للحمل",
	"Throw · place dirt": "رمي · وضع التراب",
	"Select tool": "اختيار الأداة",
	"Rotate piece": "تدوير القطعة",
	"Tilt piece": "إمالة القطعة",
	"Grid snap": "المحاذاة للشبكة",
	"Hide HUD": "إخفاء الواجهة",
	# settings tabs
	"Display": "العرض",
	"Graphics": "الرسوميات",
	"Audio": "الصوت",
	"Gameplay": "أسلوب اللعب",
	# settings labels
	"Display mode": "وضع العرض",
	"Windowed": "نافذة",
	"Borderless fullscreen": "ملء الشاشة بلا إطار",
	"Exclusive fullscreen": "ملء الشاشة الحصري",
	"Window size": "حجم النافذة",
	"V-Sync": "المزامنة الرأسية (V-Sync)",
	"Frame rate limit": "حدّ معدل الإطارات",
	"Unlimited": "بلا حد",
	"Brightness": "السطوع",
	"Contrast": "التباين",
	"Colour saturation": "تشبّع الألوان",
	"Field of view": "مجال الرؤية",
	"Quality preset": "إعداد الجودة",
	"Low": "منخفض",
	"Medium": "متوسط",
	"High": "عالٍ",
	"Ultra": "فائق",
	"Custom": "مخصص",
	"Render resolution": "دقة العرض",
	"Upscaling": "تحسين الدقة",
	"Bilinear": "خطي",
	"Anti-aliasing": "تنعيم الحواف",
	"Off": "إيقاف",
	"On": "تشغيل",
	"Shadow quality": "جودة الظلال",
	"Shadow distance": "مدى الظلال",
	"Ambient occlusion (SSAO)": "الإظلال المحيطي (SSAO)",
	"Indirect lighting (SSIL)": "الإضاءة غير المباشرة (SSIL)",
	"Screen-space reflections": "الانعكاسات (SSR)",
	"Volumetric fog": "الضباب الحجمي",
	"Bloom": "توهج الإضاءة",
	"Vegetation density": "كثافة النباتات",
	"Grass draw distance": "مدى رسم العشب",
	"Texture filtering": "فلترة الخامات",
	"Anisotropic 2×": "متباين الخواص 2×",
	"Anisotropic 4×": "متباين الخواص 4×",
	"Anisotropic 8×": "متباين الخواص 8×",
	"Anisotropic 16×": "متباين الخواص 16×",
	"Film grain": "حبيبات سينمائية",
	"Lens vignette": "تظليل أطراف العدسة",
	"Depth of field (cinematics)": "عمق الميدان (المشاهد السينمائية)",
	"Master volume": "الصوت الرئيسي",
	"Music & cinematics": "الموسيقى والمشاهد",
	"Effects": "المؤثرات",
	"Ambience (sea, wind, rain)": "الأجواء (البحر، الرياح، المطر)",
	"Interface": "الواجهة",
	"Mute when the game is in the background": "كتم الصوت عند تصغير اللعبة",
	"Output device": "جهاز الإخراج",
	"Mouse sensitivity": "حساسية الماوس",
	"Invert vertical look": "عكس النظر الرأسي",
	"Sprint: toggle instead of hold": "الركض: ضغطة للتبديل بدل الاستمرار",
	"Move forward": "تحرك للأمام",
	"Move back": "تحرك للخلف",
	"Move left": "تحرك لليسار",
	"Move right": "تحرك لليمين",
	"Jump / swim up": "قفز / سباحة للأعلى",
	"Sprint": "ركض",
	"Dive": "غوص",
	"Interact": "تفاعل",
	"Survival & journal": "النجاة واليوميات",
	"Quick eat": "أكل سريع",
	"First / third person": "منظور أول / ثالث",
	"Switch placeable": "تبديل القطعة",
	"Fast-forward time (hold)": "تسريع الوقت (استمرار)",
	"Language": "اللغة",
	"Subtitles": "الترجمة النصية",
	"Subtitle size": "حجم الترجمة",
	"Small": "صغير",
	"Large": "كبير",
	"Huge": "ضخم",
	"HUD size": "حجم الواجهة",
	"Show compass": "إظهار البوصلة",
	"Show objective": "إظهار الهدف",
	"Show control hints": "إظهار تلميحات التحكم",
	"Crosshair": "علامة التصويب",
	"Camera shake": "اهتزاز الكاميرا",
	"Head bob": "تمايل الرأس",
	"Autosave": "الحفظ التلقائي",
	"Every 2 minutes": "كل دقيقتين",
	"Every 4 minutes": "كل ٤ دقائق",
	"Every 10 minutes": "كل ١٠ دقائق",
	# loading
	"Charting the waters": "رسم خرائط المياه",
	"Raising the island": "رفع الجزيرة من البحر",
	"Carving cliffs and caves": "نحت الجروف والكهوف",
	"Growing the forest": "إنبات الغابة",
	"Waking the tide": "إيقاظ المدّ",
	"Gathering the weather": "استدعاء الطقس",
	"Letting the world settle": "تهدئة العالم",
	"Tuning the sea": "ضبط صوت البحر",
	"LOADING": "جارٍ التحميل",
	"TIP": "نصيحة",
	"Coconuts hold both food and water — your first days depend on them.": "جوز الهند يمنحك الطعام والماء معًا — أيامك الأولى تعتمد عليه.",
	"Fire keeps more than the cold away. Your mind needs it at night.": "النار لا تطرد البرد فقط… عقلك يحتاجها في الليل.",
	"Raw fish can make you sick. Cook it on a campfire first.": "السمك النيء قد يمرضك. اطبخه على النار أولًا.",
	"Everything has real weight. Logs float. Stones sink.": "لكل شيء وزن حقيقي. الخشب يطفو، والحجارة تغرق.",
	"Buildings need support. Remove a post and watch what happens.": "البناء يحتاج إلى سند. انزع عمودًا وشاهد ما يحدث.",
	"Every new game rolls a different survivor and a different truth.": "كل لعبة جديدة تمنحك ناجيًا مختلفًا… وحقيقة مختلفة.",
	"Your choices are written in your journal — and they are remembered.": "اختياراتك تُكتب في يومياتك… ولا تُنسى.",
	"When your mind breaks, the island starts to show you things.": "حين ينكسر عقلك، تبدأ الجزيرة بإظهار أشياء لك.",
	# HUD / gameplay
	"Game saved": "تم حفظ اللعبة",
	"A storm is coming…": "عاصفة قادمة…",
	"You feel sick… raw fish should be cooked first": "تشعر بالمرض… كان يجب طبخ السمك أولًا",
	"Ate %s": "أكلت %s",
	"Crafted %s": "صنعت %s",
	"Your %s broke! Craft a new one (Tab)": "انكسر %s! اصنع واحدًا جديدًا (Tab)",
	"You have no %s — craft one (Tab)": "ليس لديك %s — اصنع واحدًا (Tab)",
	"Nothing to eat — find coconuts, berries or fish": "لا يوجد ما تأكله — ابحث عن جوز الهند أو التوت أو السمك",
	"You're not tired — sleep at night or when exhausted": "لست متعبًا — نَم ليلًا أو عند الإرهاق",
	"You wake up rested — day %d": "استيقظت مرتاحًا — اليوم %d",
	"Welcome back — day %d": "مرحبًا بعودتك — اليوم %d",
	"Grid snap ON": "المحاذاة للشبكة: تشغيل",
	"Grid snap OFF": "المحاذاة للشبكة: إيقاف",
	"The collector is empty — wait for rain": "المجمّع فارغ — انتظر المطر",
	"You drink fresh rainwater": "تشرب ماء مطر عذبًا",
	"Catch fish with a spear, then cook them here": "اصطد السمك بالرمح ثم اطبخه هنا",
	"Cooking %d fish…": "يُطهى %d سمك…",
	"That was a hard fall": "كانت سقطة قوية",
	"You are drowning": "أنت تغرق",
	"Release LMB to drop   ·   RMB to throw   (%.0f kg)": "اترك الزر الأيسر للإفلات   ·   الأيمن للرمي   (%.0f كجم)",
	"Fishing spear (%d) — LMB to thrust at fish in the water": "رمح الصيد (%d) — الزر الأيسر لطعن السمك في الماء",
	"No spear — craft one (Tab)": "لا يوجد رمح — اصنع واحدًا (Tab)",
	"[E] Pick up %s   ·   Hand: hold LMB to carry": "[E] التقط %s   ·   اليد: اضغط الأيسر مطولًا للحمل",
	"Boulder (%.0f kg) — Pickaxe to break": "صخرة (%.0f كجم) — المعول لتكسيرها",
	"%s — support %d%%  ·  %s to dismantle": "%s — الدعم %d%%  ·  %s للتفكيك",
	"Cooking %d fish…  ": "يُطهى %d سمك…",
	"[E] Cook raw fish (%d)": "[E] اطبخ السمك النيء (%d)",
	"Campfire — warm yourself, cook fish here": "نار المخيم — تدفأ واطبخ السمك هنا",
	"[E] Drink rainwater (%d sips)": "[E] اشرب ماء المطر (%d رشفات)",
	"[E] Sleep until morning": "[E] نم حتى الصباح",
	"[E] Pick berries": "[E] اقطف التوت",
	"Berries will grow back tomorrow": "سينمو التوت من جديد غدًا",
	"Palm — chop for logs; coconuts may fall": "نخلة — اقطعها للخشب؛ قد يسقط جوز الهند",
	"Tree — use the Axe": "شجرة — استخدم الفأس",
	"Felled tree (%.0f kg)": "شجرة مقطوعة (%.0f كجم)",
	"Too hard for a shovel — use the pickaxe": "صلب جدًا على الجاروف — استخدم المعول",
	"No dirt or sand — dig some with the shovel": "لا يوجد تراب أو رمل — احفر بالجاروف",
	"LMB place %s   ·   B switch   ·   R/Q rotate": "الأيسر لوضع %s   ·   B تبديل   ·   R/Q تدوير",
	"No %s — craft one (Tab)   ·   B switch": "لا يوجد %s — اصنع واحدًا (Tab)   ·   B تبديل",
	"Needs flat ground": "يحتاج أرضًا مستوية",
	"LMB place %s (%d %s)   ·   B switch piece   ·   R/Q rotate   ·   F tilt   ·   G snap   ·   support %d%%":
		"الأيسر لوضع %s (%d %s)   ·   B تبديل القطعة   ·   R/Q تدوير   ·   F إمالة   ·   G محاذاة   ·   الدعم %d%%",
	"Not enough materials — chop trees (logs are sawn into planks) or mine stone": "المواد غير كافية — اقطع الأشجار (الجذوع تُنشر ألواحًا) أو استخرج الحجارة",
	"Axe": "الفأس",
	"Pickaxe": "المعول",
	"Shovel": "الجاروف",
	"Hand": "اليد",
	"Spear": "الرمح",
	"Torch": "الشعلة",
	"Build": "بناء",
	"Place": "وضع",
	# items
	"Log": "جذع",
	"Plank": "لوح",
	"Stone": "حجر",
	"Dirt": "تراب",
	"Sand": "رمل",
	"Coconut": "جوز هند",
	"Berries": "توت",
	"Raw fish": "سمك نيء",
	"Cooked fish": "سمك مطبوخ",
	"Campfire kit": "عُدّة نار",
	"Rain collector kit": "عُدّة مجمّع مطر",
	"Bed kit": "عُدّة سرير",
	"Canned food": "طعام معلّب",
	"Water bottle": "زجاجة ماء",
	"First-aid kit": "حقيبة إسعافات",
	"Red flare": "شعلة حمراء",
	"Fishing spear": "رمح صيد",
	"Beam": "عارضة",
	"Post": "عمود",
	"Panel": "لوح أرضية",
	"Stone block": "كتلة حجرية",
	"Boulder": "صخرة",
	"Fell trees, dismantle wood": "قطع الأشجار وتفكيك الخشب",
	"Break boulders and rock": "تكسير الصخور",
	"Dig and fill terrain": "الحفر والردم",
	"Catch fish in the lagoon": "صيد السمك في البحيرة",
	"Light at night (6 min)": "إضاءة ليلية (٦ دقائق)",
	"Warmth, light, cooking": "دفء وضوء وطهي",
	"Collects rain to drink": "يجمع المطر للشرب",
	"Sleep until morning, respawn point": "نوم حتى الصباح ونقطة إحياء",
	# survival panel / statuses
	"Survival": "النجاة",
	"Journal": "اليوميات",
	"You": "أنت",
	"Carrying": "تحمل",
	"Crafting": "الصناعة",
	"Tools": "الأدوات",
	"Eat": "كُل",
	"Craft": "اصنع",
	"Health": "الصحة",
	"Food": "الطعام",
	"Water": "الماء",
	"Energy": "الطاقة",
	"Mind": "العقل",
	"Body temperature  %.1f °C": "حرارة الجسم  %.1f °م",
	"Wet  %d%%": "البلل  %d%%",
	"Weight  %.0f / %.0f kg": "الوزن  %.0f / %.0f كجم",
	"Nothing yet — chop, dig, gather.": "لا شيء بعد — اقطع واحفر واجمع.",
	"Logs are sawn into planks automatically (1 log = 4 planks).": "الجذوع تُنشر ألواحًا تلقائيًا (جذع = ٤ ألواح).",
	"Coconuts give food AND water.\nCook fish on a campfire — raw fish can make you sick.\nRain collectors give fresh water.\nStay dry and near fire at night.\nSleep in a bed to skip the night.":
		"جوز الهند يعطي طعامًا وماءً.\nاطبخ السمك على النار — النيء قد يمرضك.\nمجمّع المطر يعطيك ماءً عذبًا.\nابقَ جافًا وقرب النار ليلًا.\nنَم في سرير لتتجاوز الليل.",
	"Hungry": "جائع",
	"Starving": "يتضوّر جوعًا",
	"Thirsty": "عطشان",
	"Dehydrated": "جفاف",
	"Exhausted": "منهك",
	"Cold": "بردان",
	"Freezing": "متجمّد",
	"Overheated": "حرارة زائدة",
	"Wet": "مبلل",
	"Sick": "مريض",
	"Despair": "يأس",
	"Lonely": "وحدة",
	"N": "ش",
	"NE": "شق",
	"E": "ق",
	"SE": "جق",
	"S": "ج",
	"SW": "جغ",
	"W": "غ",
	"NW": "شغ",
	# death
	"You did not survive": "لم تنجُ",
	"Keep fed, drink fresh water, stay warm and dry.": "تغذَّ واشرب ماءً عذبًا وابقَ دافئًا وجافًا.",
	"You will wake up at your bed (or the beach) and lose half of what you carried.": "ستستيقظ عند سريرك (أو على الشاطئ) وتخسر نصف ما تحمله.",
	"Wake up": "استيقظ",
	# prologue
	"SPACE — skip": "مسافة — تخطٍّ",
	"Hold SPACE to skip": "استمر بالضغط على المسافة للتخطي",
	"CAPTAIN NASSER": "القبطان ناصر",
	"LAYLA": "ليلى",
	"SAEED": "سعيد",
}
